-- PF-24: Facebook post numbers, read once a day from ScrapeCreators by
-- /api/facebook-analytics/ingest. Same shape as tt_post_performance where the
-- columns mean the same thing, so the health views and analytics functions
-- can union it as a third platform.
--
-- account     = accounts.username of the Facebook account (its page number,
--               vanity name or share/<code>), as the other tables key on handle.
-- post_id     = the story id ScrapeCreators returns as post_id; a share link
--               Yurie pastes on Posted resolves to the same number
--               (story.php?story_fbid=...), which is how delivery_id is found.
-- video_id    = the number in facebook.com/reel/<video_id>, the other way a
--               pasted link can name the reel.
-- carousel_id = the delivery's source_id (e.g. CAS-009), so content-type
--               figures pick Facebook up through unified_posts like the others.
--
-- Views are refreshed on every run while a reel is young, unlike TikTok's,
-- which are written once.

create table public.fb_post_performance (
  id               bigint generated by default as identity primary key,
  account          text        not null,
  post_id          text        not null,
  video_id         text,
  post_url         text,
  posted_at        timestamptz,
  format           text,
  caption_snippet  text,
  views            bigint,
  likes            bigint,
  comments         bigint,
  shares           bigint,
  saves            bigint,
  total_engagement bigint,
  week_of          date,
  carousel_id      text,
  delivery_id      bigint references public.post_deliveries(id) on delete set null,
  source           text        not null default 'scrapecreators',
  raw_payload      jsonb,
  first_seen_at    timestamptz not null default now(),
  ingested_at      timestamptz not null default now(),
  unique (account, post_id)
);

create index fb_post_performance_posted_at_idx on public.fb_post_performance (posted_at desc);
create index fb_post_performance_video_id_idx on public.fb_post_performance (video_id);

alter table public.fb_post_performance enable row level security;
revoke all on public.fb_post_performance from public, anon, authenticated;
grant all on public.fb_post_performance to service_role;
